version: '2'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=husain_eh
      - PASSWORD=husain1234
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=husain1234
      - POSTGRES_USER=husain_eh
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
